### ISSUE TITLE
"biid" not found

### ISSUE THREAD

**Issue by truocphan** [lamscun/Burp-Collab-Fixed#1]
How to get biid from Wireshark

**Comment by lamscun** [comment]
Please follow this steps:
- 1.  Burp Suite > Project Options > Burp Collaborator Server > Poll over unencrypted HTTP > Uncheck
- 2.  Enable capture HTTP in Wireshark 
- 3.  Burp Suite > Burp (in taskbar) > Burp Collaborator Client > Click to "Poll Now"
- 4. Now in Wireshark you will see request poll from burp, biid in url of this request

**Comment by truocphan** [comment]
Thanks bro,

**Comment by lamscun** [comment]
Fixed - please download latest replease
